stages:
  - build
  - test
  - package
  - deploy

build:
  stage: build
  image: maven:3.9.3-eclipse-temurin-17
  script:
    - mvn clean compile
  only:
    - main

test:
  stage: test
  image: maven:3.9.3-eclipse-temurin-17
  script:
    - mvn test
  only:
    - main

package:
  stage: package
  image: maven:3.9.3-eclipse-temurin-17
  script:
    - mvn clean package -DskipTests
  artifacts:
    paths:
      - target/*.jar
  only:
    - main

deploy_dev:
  stage: deploy_dev
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t bank-app:dev .
    - docker run -d -p 8080:8080 --name bank-app-dev bank-app:dev
  environment:
    name: development
    url: http://localhost:8080
  only:
    - main
